# docker-compose.yml
version: '3'
services:
  composer:
    image: composer:2.5.5
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: 'no'
  php:
    image: php:8.1.17-cli-alpine3.17
    volumes:
      - .:/app
    working_dir: /app
    restart: 'no'